apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-stack.fullname" . }}
  labels:
    {{- include "flask-stack.labels" . | nindent 4 }}
spec:
  type: {{ index .Values "flask-app" "service" "type" | default "ClusterIP" }}
  ports:
    - port: {{ index .Values "flask-app" "service" "port" | default 5000 }}
      targetPort: {{ index .Values "flask-app" "service" "port" | default 5000 }}
      protocol: TCP
      name: http
  selector:
    {{- include "flask-stack.selectorLabels" . | nindent 4 }}

